### PR TITLE
Workaround the non-portrait-orientation bug in our visibility routine.

### PR DESCRIPTION
**Pull request by wearhere**
While we work on #135, the workaround described on that bug should make it into 1.1. cc @MaxGabriel

### CODE REVIEW

**Comment by MaxGabriel** [comment]
Cool I can confirm this fixes the failing tests in the [sample project](https://github.com/MaxGabriel/SubliminalLandscapeBug) that reproed the bug.

**Comment by MaxGabriel** [comment]
For the `setOrientation` timer thing, do you maybe want something that periodically checks the orientation returned from `[[UIDevice currentDevice] orientation]`? That way you could use a longer timeout and raise a clear exception if rotation failed. (Not sure why it'd be this unreliable though)

``` objc
waitUntil(^BOOL{
        return [[UIDevice sharedDevice] orientation] == orientation;
    }, 4);
```

``` objc
void waitUntil(BOOL (^waitBlock)(void), const NSTimeInterval timeout)
{
    NSCParameterAssert(waitBlock);
    NSCParameterAssert(timeout > 0);

    NSTimeInterval timeWaited = 0;
    while (true) {

        __block BOOL waitCondition = NO;
        dispatchSyncMainQueueIfNecessary(^{
            waitCondition = waitBlock();
        });

        if (waitCondition) {
            break;
        } else if (timeWaited >= timeout) {
            NSCAssert(@"Timeout exception", @"Hit timeout waiting for an event");
        } else {
            static const NSTimeInterval sleepInterval = 0.3;
            [NSThread sleepForTimeInterval:sleepInterval];
            timeWaited += sleepInterval;
        }
    }
}

void dispatchSyncMainQueueIfNecessary(void (^block)(void))
{
    NSCParameterAssert(block);
    if ([NSThread isMainThread]) {
        block();
    } else {
        dispatch_sync(dispatch_get_main_queue(), ^{
            block();
        });
    }
}
```

**Comment by wearhere** [comment]
Oh, I think that the orientation does reliably update to that set--within the old time interval, actually, as the rotation test passes just fine. I just want to make sure that the rotation _animation_ completes by the time that `-setOrientation:` returns, 'cause otherwise it'll look a bit weird from a user's standpoint and there might be problems with visibility/tappability.

I'm not sure why the tests failed the last time, but I don't think it was due to the orientation not being set right.

**Comment by wearhere** [comment]
Found out why they failed before--on iOS 5.1 and 7.1, iPads forget their orientation when deactivated! The orientation actually becomes `UIDeviceOrientationUnknown`.

That's why [this test run](https://travis-ci.org/inkling/Subliminal/jobs/22828382) failed--when `-[SLDeviceTest testDeactivateAppForDuration]` ran before the visibility test, all the visibility test cases that test differences in behavior between Subliminal and UIAutomation started failing, because `-[SLElement isVisible]` thought that the device was in a non-portrait orientation and so used `UIAElement.isVisible` rather than Subliminal's visibility routine.

EDIT: Since this comment is linked from the commit history, I've clarified that it is _iPads_ running iOS 5.1 _or_ 7.1 that exhibit this issue.

**Comment by wearhere** [comment]
Aaand `UIDevice` forgets on iOS 7.1 too >.<.

**Comment by MaxGabriel** [comment]
I wasn't able to replicate it, but maybe calling `beginGeneratingDeviceOrientationNotifications` before this test would fix it?

**Comment by wearhere** [comment]
Further clarification: I see `-[SLDeviceTest testThatDeviceOrientationPersistsThroughDeactivation]` consistently fail on the _iPad_ when running either iOS 5.1 or 7.1 (but 6.1's fine).

I don't doubt that it might work without the reset in some circumstances--in [this run](https://travis-ci.org/inkling/Subliminal/jobs/23372969), _some_ of the visibility test cases failed in a way that would suggest that the orientation had been forgotten, but not all, and `-[SLDeviceTest testThatDeviceOrientationPersistsThroughDeactivation]` passed there.

Calling `-[UIDevice beginGeneratingDeviceOrientationNotifications]` didn't seem to help fwiw.

**Pull request merged**
