### PR TITLE
Update README and xcconfig to remove the "Integration Tests-Info.plist" setting

### PR DESCRIPTION
**Pull request by MaxGabriel**
Implementation of #144

The existing README images come from the Subliminal website (which is from the gh-pages branch I assume). I added a directory for documentation images to the master branch, since otherwise I would need a second PR to the gh-pages branch. I can make a separate PR to gh-pages if you want to keep all the images on inkling.github.io/Subliminal

### CODE REVIEW

**Comment by MaxGabriel** [comment]
Tested this here https://github.com/MaxGabriel/SubliminalSamePlist and Subliminal's working fine.

I did run into several failed attempts at starting the iOS simulator—I think that's just normal simulator wonkiness, though.

**Comment by wearhere** [comment]
I think this is a good idea @MaxGabriel. Anything we can do to slim down the installation instructions is a good idea, and not having to keep two plists in sync is a definite plus. I would like you to add the image to `gh-pages` rather than `master` though, so users don't have to download the documentation images. (The idea behind moving the installation instructions to the Wiki (#82) is that users probably don't need to have them downloaded locally at all, considering that they'll probably install just once, at the same time as they're checking out the repo.)

Also, I'd like to leave the `INFOPLIST_FILE` setting in the `xcconfig` file. Like you suggested, it won't take effect if the user follows your new instructions, so no reason to break existing installations.

Once you've made these changes I'm good to merge. Thanks for your thoroughness in testing as always!

**Comment by wearhere** [comment]
It would be nice to add a comment to the `xcconfig` file about the setting being maintained for historical reasons though.

**Comment by MaxGabriel** [comment]
Awesome. I'll make those changes. I'll probably add in #146 to this PR as well, since some of the README changes can be dropped entirely if #146 is implemented, too.

**Comment by MaxGabriel** [comment]
Ok, should be ready, but depends on #149. This PR also resolves #146

**Comment by MaxGabriel** [comment]
Updated [the test project](https://github.com/MaxGabriel/SubliminalSamePlist) with the new xcconfig file (just copy+pasted it across) and gave it a Product Name so it no longer uses the xcconfig file one. Integration Tests run fine.

**Comment by wearhere** [comment]
Looks good!

**Pull request merged**
